parameters:
  evlz_pest.rest.class: Evlz\PestBundle\Entity\RestClient
  evlz_pest.json_rest.class: Evlz\PestBundle\Entity\JSONRestClient

services:
  evlz_pest.rest:
    class: %evlz_pest.rest.class%
  evlz_pest.rest_json:
    class: %evlz_pest.json_rest.class%